#This playbbok will install HTTP server and will not start the server.

---
- hosts: all
  become: true
  tasks:
    - name: Install Apache2 
      apt: name=apache2 update_cache=yes state=latest
...
